import { FormEvent, useEffect, useMemo, useState } from "react";
import { Loader2, Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import PageWrap from "../components/layout/PageWrap";
import Button from "../components/ui/Button";
import Input from "../components/ui/Input";
import { createLectureSchedule, deleteLectureSchedule, fetchClassSections, fetchLectureSchedules, fetchTeachers } from "../services/api";
import type { ClassSection, LectureSchedule, Teacher } from "../types";

const DAYS = [[0,"Monday"],[1,"Tuesday"],[2,"Wednesday"],[3,"Thursday"],[4,"Friday"],[5,"Saturday"],[6,"Sunday"]] as const;
const EMPTY_FORM = { subject:"", classSectionId:"", teacherId:"", day:"0", start:"", end:"", startDate:"", endDate:"" };

export default function WeeklySchedulePage() {
  const [schedules,setSchedules]=useState<LectureSchedule[]>([]); const [sections,setSections]=useState<ClassSection[]>([]); const [teachers,setTeachers]=useState<Teacher[]>([]);
  const [form,setForm]=useState(EMPTY_FORM); const [loading,setLoading]=useState(true); const [submitting,setSubmitting]=useState(false); const [deletingId,setDeletingId]=useState<number|null>(null);
  async function load(){ setLoading(true); try { const [w,s,t]=await Promise.all([fetchLectureSchedules(),fetchClassSections(),fetchTeachers()]); setSchedules(w); setSections(s); setTeachers(t); } catch(e:any){toast.error(e?.message||"Failed to load weekly schedule");} finally{setLoading(false);} }
  useEffect(()=>{void load();},[]);
  const sectionName=(id:number|null|undefined)=>{const s=sections.find(x=>x.id===id);return s?`${s.department} · ${s.class_name} · ${s.section}`:"Unassigned";};
  const grouped=useMemo(()=>DAYS.map(([day])=>({day,schedules:schedules.filter(x=>x.day_of_week===day).sort((a,b)=>a.start_time.localeCompare(b.start_time))})),[schedules]);
  async function submit(e:FormEvent){e.preventDefault(); if(!form.subject.trim()||!form.classSectionId||!form.start||!form.end||!form.startDate){toast.error("Subject, class section, effective start date and times are required");return;} if(form.end<=form.start){toast.error("End time must be after start time");return;} if(form.endDate&&form.endDate<form.startDate){toast.error("Effective end date must be on or after the start date");return;} setSubmitting(true); try { await createLectureSchedule({subject:form.subject.trim(),class_section_id:Number(form.classSectionId),teacher_id:form.teacherId?Number(form.teacherId):null,day_of_week:Number(form.day),start_time:form.start,end_time:form.end,effective_start_date:form.startDate,effective_end_date:form.endDate||null}); setForm(EMPTY_FORM); await load(); toast.success("Weekly schedule created"); } catch(e:any){toast.error(e?.message||"Could not create weekly schedule");} finally{setSubmitting(false);} }
  async function remove(schedule:LectureSchedule){if(!confirm(`Delete ${schedule.subject} from the recurring timetable? Existing generated lectures will remain.`))return;setDeletingId(schedule.id);try{await deleteLectureSchedule(schedule.id);await load();toast.success("Weekly schedule deleted");}catch(e:any){toast.error(e?.message||"Could not delete weekly schedule");}finally{setDeletingId(null);}}
  if(loading)return <PageWrap><div className="flex min-h-64 items-center justify-center gap-3 text-slate-400"><Loader2 size={20} className="animate-spin"/><span>Loading weekly schedule…</span></div></PageWrap>;
  return <PageWrap>
    <div className="mb-6"><h1 className="text-2xl font-bold text-white">Weekly Schedule</h1><p className="mt-1 text-sm text-slate-400">This is the recurring timetable. Dated lectures are generated automatically from these templates.</p></div>
    <form onSubmit={submit} className="mb-6 grid gap-3 rounded-2xl border border-white/10 bg-white/5 p-5 md:grid-cols-3">
      <Input label="Subject" value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} disabled={submitting} placeholder="Database Management"/>
      <label className="block"><span className="mb-1.5 block text-sm font-medium text-slate-300">Class Section</span><select required disabled={submitting} value={form.classSectionId} onChange={e=>setForm({...form,classSectionId:e.target.value})} className="w-full rounded-xl border border-white/10 bg-[#0F172A] px-3 py-2.5 text-sm text-white"><option value="">Select class section</option>{sections.map(s=><option key={s.id} value={s.id}>{sectionName(s.id)}</option>)}</select></label>
      <label className="block"><span className="mb-1.5 block text-sm font-medium text-slate-300">Teacher</span><select disabled={submitting} value={form.teacherId} onChange={e=>setForm({...form,teacherId:e.target.value})} className="w-full rounded-xl border border-white/10 bg-[#0F172A] px-3 py-2.5 text-sm text-white"><option value="">Select teacher (optional)</option>{teachers.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>
      <label className="block"><span className="mb-1.5 block text-sm font-medium text-slate-300">Day</span><select disabled={submitting} value={form.day} onChange={e=>setForm({...form,day:e.target.value})} className="w-full rounded-xl border border-white/10 bg-[#0F172A] px-3 py-2.5 text-sm text-white">{DAYS.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>
      <Input label="Start" type="time" value={form.start} onChange={e=>setForm({...form,start:e.target.value})} disabled={submitting}/><Input label="End" type="time" value={form.end} onChange={e=>setForm({...form,end:e.target.value})} disabled={submitting}/>
      <Input label="Effective From" type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})} disabled={submitting}/><Input label="Effective Until (optional)" type="date" value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})} disabled={submitting}/>
      <Button type="submit" className="mt-auto" disabled={submitting}>{submitting?<><Loader2 size={16} className="animate-spin"/> Saving…</>:<><Plus size={16}/> Add Schedule</>}</Button>
    </form>
    <div className="grid gap-4 lg:grid-cols-2 xl:grid-cols-3">{grouped.map(({day,schedules:daySchedules})=>{const dayName=DAYS.find(([id])=>id===day)?.[1]||"Day";return <section key={day} className="overflow-hidden rounded-2xl border border-white/10 bg-white/5"><div className="border-b border-white/10 bg-white/[0.03] px-4 py-3"><h2 className="text-sm font-semibold text-white">{dayName}</h2><p className="mt-0.5 text-xs text-slate-500">{daySchedules.length} recurring {daySchedules.length===1?"lecture":"lectures"}</p></div>{daySchedules.length===0?<div className="p-5 text-sm text-slate-500">No lectures scheduled.</div>:<div className="divide-y divide-white/5">{daySchedules.map(s=><div key={s.id} className="flex items-start justify-between gap-3 p-4"><div className="min-w-0"><div className="text-sm font-medium text-slate-100">{s.subject}</div><div className="mt-1 text-xs font-medium text-slate-300">{s.start_time} – {s.end_time}</div><div className="mt-1 text-xs text-slate-500">{sectionName(s.class_section_id)} · {teachers.find(t=>t.id===s.teacher_id)?.name||"No teacher"}</div><div className="mt-1 text-xs text-slate-500">{s.effective_start_date||"Any date"}{s.effective_end_date?` → ${s.effective_end_date}`:" → ongoing"}</div></div><button type="button" disabled={deletingId!==null} onClick={()=>void remove(s)} className="shrink-0 rounded-lg p-2 text-slate-400 hover:bg-red-500/10 hover:text-red-400 disabled:opacity-50">{deletingId===s.id?<Loader2 size={15} className="animate-spin"/>:<Trash2 size={15}/>}</button></div>)}</div>}</section>})}</div>
  </PageWrap>;
}
